# Generated by Django 5.2.8 on 2025-11-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_designrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
